// Quaesitor - Core Types
//
import type { VerificationReport } from "./citation-verifier";
//
// The pipeline is designed to surpass single-round research tools by adding:
//   1. A research PLAN (structured outline generated up-front).
//   2. GAP ANALYSIS after round 1 — the agent reviews findings and identifies
//      what's missing, then generates follow-up questions.
//   3. A SECOND RESEARCH ROUND to fill the gaps.
//   4. Final SYNTHESIS that follows the plan's outline.

export type ResearchStatus =
  | "queued"
  | "planning"
  | "decomposing"
  | "searching"
  | "reading"
  | "extracting"
  | "analyzing_gaps"
  | "synthesizing"
  | "completed"
  | "failed";

export type SubQueryStatus =
  | "pending"
  | "searching"
  | "reading"
  | "extracting"
  | "done"
  | "failed";

export type SubQueryRound = 1 | 2;

// SearchDepth — the four research-depth presets exposed to the user via
// the DepthIndicator UI (Quick / Standard / Deep / Advanced).
//   - quick     — 1 sub-query, 3 links, no multi-round. Fastest.
//   - standard  — 3 sub-queries, 4 links, no multi-round.
//   - deep      — 5 sub-queries, 8 links, 2 gap queries, multi-round.
//   - advanced  — 7+ sub-queries, 15 links, 3 gap queries, multi-round.
// "quick" was added to fix the UI↔API type mismatch (the UI offered
// "quick" but the API rejected it with a 400). All four values are now
// valid everywhere — DepthIndicator, zod schemas, resolveConfig presets.
export type SearchDepth = "quick" | "standard" | "deep" | "advanced";

export type RetrieverType = "duckduckgo";

export type LLMProvider = "nvidia";

export interface ResearchConfig {
  query: string;
  depth: SearchDepth;
  numSubQueries: number;
  maxLinksPerQuery: number;
  pageReadConcurrency: number;
  reportMaxTokens: number;
  retriever: RetrieverType;
  llmProvider: LLMProvider;
  // Multi-round research (the key differentiator vs. single-round tools).
  enableMultiRound: boolean;
  // How many gap-filling sub-queries to generate in round 2.
  numGapQueries: number;
}

// a section of the research plan
export interface PlanSection {
  id: string;
  title: string;
  description: string;
}

export interface ResearchPlan {
  title: string;
  summary: string;
  sections: PlanSection[];
}

export interface SearchResultItem {
  url: string;
  name: string;
  snippet: string;
  host_name: string;
  rank: number;
  date: string;
  favicon: string;
}

export interface PageReadResult {
  url: string;
  title: string;
  text: string;
  publishedTime?: string;
  success: boolean;
  error?: string;
  tokensUsed: number;
  wordCount: number;
}

export interface Source {
  url: string;
  title: string;
  host: string;
  snippet: string;
  subQueryId: string;
  round: SubQueryRound;
  publishedTime?: string;
  excerpt?: string;
  tokensUsed?: number;
  wordCount?: number;
}

export interface SubQuery {
  id: string;
  question: string;
  status: SubQueryStatus;
  round: SubQueryRound;
  // For round-2 sub-queries, the gap they're meant to fill.
  rationale?: string;
  searchResults: SearchResultItem[];
  pagesRead: number;
  pagesSucceeded: number;
  keyFindings: string;
  startedAt?: number;
  finishedAt?: number;
  error?: string;
}

export interface LogEntry {
  ts: number;
  level: "info" | "warn" | "error" | "success";
  stage: ResearchStatus;
  message: string;
}

//: "Thinking" entries — human-readable thoughts the model
// produces during research. Unlike LogEntry (technical), these are meant
// for the user to read: "I found that X... I want to explore Y next..."
export interface ThoughtEntry {
  ts: number;
  stage: ResearchStatus;
  text: string;
  // Optional: what the model plans to do next
  plan?: string;
}

export interface ResearchStats {
  totalPagesFound: number;
  totalPagesRead: number;
  totalPagesSucceeded: number;
  totalTokensUsed: number;
  elapsedMs: number;
  subQueriesCompleted: number;
  roundsCompleted: number;
  // Cost tracking (Phase 2A.5)
  llmCalls: number;
  inputTokens: number;
  outputTokens: number;
  estimatedCost: number; // USD
}

export interface ResearchJob {
  id: string;
  query: string;
  status: ResearchStatus;
  createdAt: number;
  updatedAt: number;
  startedAt?: number;
  finishedAt?: number;
  // A-3: userId is part of the research-cache key — keeps one user's cached
  // results from being served to another user. Defaults to "default" for
  // unauthenticated deployments and for jobs reconstructed from the DB
  // (which predates this column).
  userId?: string;
  config: ResearchConfig;
  plan: ResearchPlan | null;
  gapAnalysis: string | null;
  // Follow-up questions generated by gap analysis, used to drive round 2.
  // (Previously stored via a `_followUps` type-assertion hack — now a proper field.)
  round2FollowUps: string[];
  subQueries: SubQuery[];
  sources: Source[];
  report: string | null;
  logs: LogEntry[];
  //: human-readable thoughts shown in the "thinking panel"
  thoughts: ThoughtEntry[];
  error: string | null;
  stats: ResearchStats;
  // Client IP for rate-limit bookkeeping (never serialized to the client).
  clientIP?: string;
  // Cancellation flag. Set by /api/research/stop. The pipeline checks this
  // before each major stage and throws if true.
  cancelled: boolean;
  // AbortController for real cancellation of in-flight HTTP requests.
  // When the user clicks Stop, abort() is called — all active fetch() calls
  // (search, page reads) throw AbortError immediately instead of completing.
  abortController?: AbortController;
  // Streaming report: tokens are pushed here as they arrive from the LLM.
  // The SSE endpoint reads this buffer and emits "report_token" events.
  reportStream: string[];
  // True while the report is being streamed (synthesis stage).
  reportStreaming: boolean;
  // FOLLOW-UP QUESTIONS: generated after the report, let the user dig deeper.
  followUpQuestions: string[];
  // CLARIFYING QUESTIONS: generated before research starts, if the query
  // is ambiguous. The user can answer them to refine the research.
  clarifyingQuestions: string[];
  // CITATION VERIFICATION (Phase 2A): after synthesis, all citations in the
  // report are checked against job.sources. URLs not in sources = unverified.
  verificationReport?: VerificationReport | null;
}

// Public-facing shape (sent to the client). Strips large text fields if needed.
export type ResearchJobPublic = Omit<ResearchJob, "logs"> & {
  logs: LogEntry[];
};

export function toPublicJob(job: ResearchJob): ResearchJobPublic {
  return { ...job };
}
