// Video Understanding — MINIMAL STUB.
//
// This module was previously an interface-only stub that returned
// empty results from `analyzeVideo`. As of v4.1.0 (final-10 task)
// the stub surface has been reduced to the minimum the API route
// (`/api/video/analyze`) needs to compile and return a clean 503.
//
// STATUS: Not implemented. The full implementation requires ffmpeg +
// ffprobe binaries on the host + openai-whisper (or a hosted
// Whisper-compatible API) for transcription. The plan to wire it up
// is documented in `docs/MIGRATION_NOTES.md` under the (now-archived)
// "Stub modules" section.
//
// What's here:
//   - Type exports (`VideoKeyframe`, `VideoTranscript`, `VideoScene`,
//     `VideoAnalysis`, `AnalyzeVideoOptions`) — kept so the API
//     route's type annotations compile without changes.
//   - `isVideoUnderstandingAvailable()` — always returns `false`.
//     The API route checks this first and returns 503 BEFORE calling
//     `analyzeVideo`, so the route degrades cleanly to "feature
//     unavailable" without ever throwing.
//   - `analyzeVideo()` — throws `"Not implemented: video understanding
//     requires ffmpeg + Whisper"`. Defensive only; the API route
//     never reaches this call because `isVideoUnderstandingAvailable`
//     gates it.
//   - `extractKeyframes()` / `transcribeVideo()` / `buildVideoPrompt()` —
//     throw the same "Not implemented" error. Kept as stubs so any
//     future caller that imports them gets a clean runtime error
//     instead of an `undefined is not a function` crash.
//   - `VIDEO_CONFIG` — informational constants exported for admin
//     dashboards that read the planned limits.
//
// To re-enable (future milestone):
//   1. `apt install ffmpeg` + `pip install openai-whisper` on the host.
//   2. Set `VIDEO_UNDERSTANDING_ENABLED=true` in the environment.
//   3. Replace the `analyzeVideo` body with the four-step pipeline
//      (ffprobe → keyframe extraction → audio extraction → whisper
//      transcription). The old stub body is in git history.
//   4. Update `isVideoUnderstandingAvailable` to honour the env flag
//      again (return `process.env.VIDEO_UNDERSTANDING_ENABLED === "true"`).

export interface VideoKeyframe {
  /** Timestamp of the frame in the source video, in seconds. */
  timestamp: number;
  /** JPEG thumbnail as a base64 data URI (no `data:image/jpeg;base64,` prefix). */
  base64: string;
  /** Optional natural-language description of the frame, generated by a vision model. */
  description?: string;
}

export interface VideoTranscript {
  segments: Array<{
    /** Start time of the segment, in seconds. */
    start: number;
    /** End time of the segment, in seconds. */
    end: number;
    /** Transcribed text for this segment. */
    text: string;
  }>;
  /** Convenience: all segments joined with a space. */
  fullText: string;
}

export interface VideoScene {
  /** Start time of the scene, in seconds. */
  start: number;
  /** End time of the scene, in seconds. */
  end: number;
  /** Short human-readable label (e.g. "Introduction", "Demo", "Q&A"). */
  label: string;
}

export interface VideoAnalysis {
  /** Total duration in seconds. */
  duration: number;
  /** Extracted keyframes (thumbnails). Empty if extraction failed. */
  keyframes: VideoKeyframe[];
  /** Audio transcript, or null if transcription failed / not requested. */
  transcript: VideoTranscript | null;
  /** Source video metadata (from ffprobe). */
  metadata: {
    width: number;
    height: number;
    fps: number;
    codec: string;
  };
  /** Natural-language summary of the video. */
  summary?: string;
  /** Scene boundaries detected via optical-flow analysis. */
  scenes?: VideoScene[];
}

export interface AnalyzeVideoOptions {
  /** Extract one keyframe every N seconds. Default: 5. */
  keyframeInterval?: number;
  /** Maximum number of keyframes to extract. Default: 20. */
  maxKeyframes?: number;
  /** Whether to also transcribe the audio track. Default: true. */
  transcribe?: boolean;
}

/**
 * Whether video understanding is available on this server.
 *
 * Always returns `false` — the full implementation is not wired up.
 * The API route checks this BEFORE calling `analyzeVideo`, so callers
 * receive a clean 503 ("Video understanding is not available on this
 * server") instead of hitting the "Not implemented" throw.
 *
 * When the real implementation lands, this should return
 * `process.env.VIDEO_UNDERSTANDING_ENABLED === "true"` (gated on the
 * env flag + host-side ffmpeg + Whisper installation).
 */
export function isVideoUnderstandingAvailable(): boolean {
  return false;
}

/**
 * Alias for `isVideoUnderstandingAvailable()` — kept for compatibility
 * with the task spec's preferred name.
 *
 * @deprecated prefer `isVideoUnderstandingAvailable()` in new code.
 */
export function isVideoAnalysisAvailable(): boolean {
  return isVideoUnderstandingAvailable();
}

/**
 * Video-analysis configuration constants. Informational — surfaced for
 * admin dashboards that want to render the planned limits without
 * grepping the source.
 */
export const VIDEO_CONFIG = {
  maxDuration: 600,
  keyframeInterval: 5,
  maxKeyframes: 120,
  transcriptModel: "whisper-1",
} as const;

/**
 * Analyze a video — NOT IMPLEMENTED.
 *
 * Always throws. The API route (`/api/video/analyze`) gates on
 * `isVideoUnderstandingAvailable()` first and returns 503 if false,
 * so callers never reach this throw in normal operation. The throw
 * is defensive: if a future caller invokes `analyzeVideo` directly
 * (bypassing the route's availability check), they get a clean error
 * message instead of an `undefined` crash.
 *
 * @throws Error "Not implemented: video understanding requires ffmpeg + Whisper"
 */
export async function analyzeVideo(
  _videoPath: string,
  _options: AnalyzeVideoOptions = {}
): Promise<VideoAnalysis> {
  throw new Error(
    "Not implemented: video understanding requires ffmpeg + Whisper. " +
      "See docs/MIGRATION_NOTES.md for the implementation plan."
  );
}

/**
 * Extract keyframes from a video — NOT IMPLEMENTED.
 *
 * @throws Error "Not implemented: video understanding requires ffmpeg + Whisper"
 */
export async function extractKeyframes(
  _videoPath: string,
  _intervalSeconds = 5,
  _maxFrames = 20
): Promise<VideoKeyframe[]> {
  throw new Error(
    "Not implemented: video understanding requires ffmpeg + Whisper. " +
      "See docs/MIGRATION_NOTES.md for the implementation plan."
  );
}

/**
 * Transcribe a video's audio track — NOT IMPLEMENTED.
 *
 * @throws Error "Not implemented: video understanding requires ffmpeg + Whisper"
 */
export async function transcribeVideo(_videoPath: string): Promise<VideoTranscript> {
  throw new Error(
    "Not implemented: video understanding requires ffmpeg + Whisper. " +
      "See docs/MIGRATION_NOTES.md for the implementation plan."
  );
}

/**
 * Build a vision-model prompt from a video analysis.
 *
 * This is a pure function (no I/O) so it's safe to keep — but it's
 * only useful when paired with a real `analyzeVideo` result. Kept as
 * a stub that throws to surface any caller that depends on the
 * video-understanding pipeline without realizing it's not wired up.
 *
 * @throws Error "Not implemented: video understanding requires ffmpeg + Whisper"
 */
export function buildVideoPrompt(_analysis: VideoAnalysis, _question: string): string {
  throw new Error(
    "Not implemented: video understanding requires ffmpeg + Whisper. " +
      "See docs/MIGRATION_NOTES.md for the implementation plan."
  );
}
