// STUB: Full implementation requires ffmpeg + whisper. See docs/MIGRATION_NOTES.md
//
// Video Understanding — extract keyframes + audio transcript for vision models.
//
// P2-final-wave / Feature 3: interface + stubs for video analysis. Real
// implementation requires ffmpeg (for keyframe extraction + ffprobe for
// metadata) and Whisper (for audio transcription). This module provides
// the type contracts + a stub implementation that returns empty results
// so callers can be written against the interface today; the actual
// ffmpeg + Whisper wiring is a future infrastructure milestone.
//
// When `VIDEO_UNDERSTANDING_ENABLED=true` is set AND ffmpeg + Whisper
// are installed on the host, the real implementation (TODO: wire up
// child_process.execFile calls) would:
//   1. Run `ffprobe -v quiet -print_format json -show_format -show_streams`
//      to get duration, resolution, fps, codec.
//   2. Run `ffmpeg -i input.mp4 -vf fps=1/N frame_%04d.jpg` to extract
//      one keyframe every N seconds (default 5s, capped at maxKeyframes).
//   3. Run `ffmpeg -i input.mp4 -vn -acodec pcm_s16le audio.wav` to
//      extract the audio track, then `whisper audio.wav --model small`
//      to transcribe (returns segments with start/end/text).
//   4. Return a VideoAnalysis with all of the above, ready to feed into
//      `buildVideoPrompt()` for a vision model query.
//
// SECURITY: the `videoPath` is server-controlled (the caller validates it
// against an allow-list of upload directories before invoking). We never
// shell-escape user input — we pass it as an argv element to execFile,
// which avoids shell-injection entirely.

export interface VideoKeyframe {
  /** Timestamp of the frame in the source video, in seconds. */
  timestamp: number;
  /** JPEG thumbnail as a base64 data URI (no `data:image/jpeg;base64,` prefix). */
  base64: string;
  /**
   * Optional natural-language description of the frame, generated by a
   * vision model (e.g. "A whiteboard with three boxes labeled
   * 'ingestion', 'processing', 'output'"). When the real implementation
   * is wired up, this is produced by feeding the keyframe into the
   * configured vision provider (OpenAI GPT-4o / Anthropic Claude 3.5
   * / NVIDIA Llama 3.2 Vision — same fallback chain as `/api/vision`).
   *
   * The description gives a vision-model chat turn the temporal context
   * that pure image inputs can't convey ("at 0:35, the speaker holds up
   * a chart showing…"). Without it, the model only sees the pixels.
   */
  description?: string;
}

export interface VideoTranscript {
  segments: Array<{
    /** Start time of the segment, in seconds. */
    start: number;
    /** End time of the segment, in seconds. */
    end: number;
    /** Transcribed text for this segment. */
    text: string;
  }>;
  /** Convenience: all segments joined with a space. */
  fullText: string;
}

export interface VideoScene {
  /** Start time of the scene, in seconds. */
  start: number;
  /** End time of the scene, in seconds. */
  end: number;
  /** Short human-readable label (e.g. "Introduction", "Demo", "Q&A"). */
  label: string;
}

export interface VideoAnalysis {
  /** Total duration in seconds. */
  duration: number;
  /** Extracted keyframes (thumbnails). Empty if extraction failed. */
  keyframes: VideoKeyframe[];
  /** Audio transcript, or null if transcription failed / not requested. */
  transcript: VideoTranscript | null;
  /** Source video metadata (from ffprobe). */
  metadata: {
    width: number;
    height: number;
    fps: number;
    codec: string;
  };
  /**
   * Natural-language summary of the video, generated by feeding the
   * keyframes + transcript into a vision/language model. Empty string
   * when the real implementation isn't wired up. The summary gives a
   * chat turn a quick orientation without having to scan every
   * keyframe individually.
   */
  summary?: string;
  /**
   * Scene boundaries detected via optical-flow analysis (ffmpeg's
   * `select=gt(scene\,0.4)` filter). Each scene is a labeled time
   * range — the label is generated by clustering keyframes within the
   * scene and asking the vision model for a one-phrase description.
   * Empty when the real implementation isn't wired up.
   */
  scenes?: VideoScene[];
}

export interface AnalyzeVideoOptions {
  /** Extract one keyframe every N seconds. Default: 5. */
  keyframeInterval?: number;
  /** Maximum number of keyframes to extract. Default: 20. */
  maxKeyframes?: number;
  /** Whether to also transcribe the audio track. Default: true. */
  transcribe?: boolean;
}

/**
 * Whether video understanding is available on this server.
 *
 * Set `VIDEO_UNDERSTANDING_ENABLED=true` in the environment AND install
 * ffmpeg + Whisper on the host. The flag is the single source of truth —
 * callers should check this BEFORE attempting to analyze a video so they
 * can return a clean 503 to the client instead of a confusing stub result.
 */
export function isVideoUnderstandingAvailable(): boolean {
  return process.env.VIDEO_UNDERSTANDING_ENABLED === "true";
}

/**
 * Alias for `isVideoUnderstandingAvailable()` — kept for compatibility
 * with the task spec's preferred name. Some callers (e.g. the public
 * API docs) refer to "video analysis" rather than "video understanding";
 * this alias lets either name resolve to the same check.
 *
 * @deprecated prefer `isVideoUnderstandingAvailable()` in new code —
 *             the codebase standardizes on "understanding" (matches
 *             the env-var name `VIDEO_UNDERSTANDING_ENABLED`).
 */
export function isVideoAnalysisAvailable(): boolean {
  return isVideoUnderstandingAvailable();
}

/**
 * Video-analysis configuration constants. These are the defaults used
 * by `analyzeVideo()` when the caller doesn't override them via
 * `AnalyzeVideoOptions`. They're exported as a single object so an
 * admin dashboard (or operator docs) can render them without having
 * to grep the source.
 *
 * - `maxDuration` — videos longer than this (in seconds) are rejected
 *   before processing. 600s (10 min) matches Whisper's comfortable
 *   single-call limit on the `small` model; longer videos should be
 *   chunked (a future TODO).
 * - `keyframeInterval` — one keyframe every N seconds. 5s is a good
 *   balance between temporal resolution and token cost (a 10-min
 *   video → 120 keyframes → 120 image tokens in the vision-model call).
 * - `maxKeyframes` — hard cap on keyframes regardless of duration.
 *   120 keeps a 10-min video at exactly the cap; longer videos are
 *   subsampled (interval grows to fit).
 * - `transcriptModel` — Whisper model id used by the real implementation.
 *   `"whisper-1"` is the OpenAI Whisper API model; local Whisper uses
 *   `--model small` (not an id). The flag is informational for now.
 */
export const VIDEO_CONFIG = {
  maxDuration: 600,
  keyframeInterval: 5,
  maxKeyframes: 120,
  transcriptModel: "whisper-1",
} as const;

/**
 * Analyze a video: extract metadata, keyframes, and (optionally) an
 * audio transcript. The result is structured for direct consumption by
 * vision models (keyframes become image inputs; transcript becomes text).
 *
 * @throws if `isVideoUnderstandingAvailable()` returns false. Callers
 *         should check availability first and return a 503 to the client.
 *
 * STUB: returns an empty analysis. Real implementation is gated behind
 * `VIDEO_UNDERSTANDING_ENABLED=true` + ffmpeg + Whisper installation.
 */
export async function analyzeVideo(
  videoPath: string,
  options: AnalyzeVideoOptions = {}
): Promise<VideoAnalysis> {
  if (!isVideoUnderstandingAvailable()) {
    throw new Error(
      "Video understanding is not available. Set VIDEO_UNDERSTANDING_ENABLED=true " +
        "and install ffmpeg + Whisper."
    );
  }

  // Validate the path — must be a non-empty string. The actual path-
  // allow-list check (against upload directories) is the caller's
  // responsibility; we just sanity-check the shape here.
  if (typeof videoPath !== "string" || videoPath.trim().length === 0) {
    throw new Error("videoPath must be a non-empty string.");
  }

  const { keyframeInterval = 5, maxKeyframes = 20, transcribe = true } = options;

  // Real implementation would:
  // 1. Run ffprobe to get metadata (duration, width, height, fps, codec).
  // 2. Run ffmpeg to extract keyframes (1 per `keyframeInterval` seconds,
  //    capped at `maxKeyframes`).
  // 3. If `transcribe`, extract audio with ffmpeg and run Whisper.
  // 4. Return structured analysis.
  //
  // For now, return an empty analysis so callers can develop against the
  // interface. The TODO below marks the wiring points.
  void keyframeInterval;
  void maxKeyframes;
  void transcribe;
  // TODO(p2-final-wave): wire up ffprobe + ffmpeg + Whisper here.

  return {
    duration: 0,
    keyframes: [],
    transcript: null,
    metadata: { width: 0, height: 0, fps: 0, codec: "unknown" },
    summary:
      "Video analysis requires ffmpeg + Whisper. Set VIDEO_UNDERSTANDING_ENABLED=true and install both to enable.",
    scenes: [],
  };
}

/**
 * Extract keyframes from a video at a fixed interval.
 *
 * Real implementation: `ffmpeg -i input.mp4 -vf fps=1/{interval} frame_%04d.jpg`
 * then read each frame file as base64 and delete the temp files.
 *
 * @returns array of keyframes (timestamp + base64 JPEG). Empty if the
 *          real implementation isn't wired up yet.
 */
export async function extractKeyframes(
  videoPath: string,
  intervalSeconds = 5,
  maxFrames = 20
): Promise<VideoKeyframe[]> {
  if (!isVideoUnderstandingAvailable()) return [];
  // TODO(p2-final-wave): ffmpeg -i {videoPath} -vf fps=1/{interval} frame_%04d.jpg
  void videoPath;
  void intervalSeconds;
  void maxFrames;
  return [];
}

/**
 * Transcribe a video's audio track using Whisper.
 *
 * Real implementation: extract audio (`ffmpeg -i input.mp4 -vn audio.wav`),
 * then run `whisper audio.wav --model small --output_format json` and
 * parse the JSON segments.
 *
 * @returns transcript with segments + fullText. Empty if the real
 *          implementation isn't wired up yet.
 */
export async function transcribeVideo(videoPath: string): Promise<VideoTranscript> {
  if (!isVideoUnderstandingAvailable()) {
    return { segments: [], fullText: "" };
  }
  // TODO(p2-final-wave): ffmpeg audio extraction + whisper transcription.
  void videoPath;
  return { segments: [], fullText: "" };
}

/**
 * Build a vision-model prompt from a video analysis.
 *
 * The prompt summarizes the video's metadata, lists keyframe timestamps,
 * and includes (a truncated) transcript. The vision model receives the
 * keyframes as image inputs alongside this text prompt — the text gives
 * it the temporal + audio context that pure image inputs can't convey.
 *
 * @param analysis the result of `analyzeVideo()`.
 * @param question the user's question about the video.
 * @returns a single string prompt suitable for a vision-model chat turn.
 */
export function buildVideoPrompt(analysis: VideoAnalysis, question: string): string {
  const parts: string[] = [
    `Video duration: ${analysis.duration}s`,
    `Resolution: ${analysis.metadata.width}x${analysis.metadata.height}`,
    `Keyframes: ${analysis.keyframes.length} (1 per ${
      analysis.keyframes.length > 0
        ? Math.floor(analysis.duration / analysis.keyframes.length)
        : 0
   }s)`,
  ];
  if (analysis.transcript && analysis.transcript.fullText) {
    // Truncate the transcript to 2000 chars — vision models have a
    // limited context window, and the keyframes carry most of the
    // visual information anyway. The transcript is supplementary.
    parts.push(`Transcript: ${analysis.transcript.fullText.slice(0, 2000)}`);
  }
  parts.push(`Question: ${question}`);
  return parts.join("\n");
}
