// Verify-email — sent on signup to confirm the email address.
//
// Contains a one-click verification link. The token is generated by the
// caller (route handler) and stored server-side; this template just renders it.

import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Heading,
  Text,
  Button,
  Hr,
  Link,
} from "@react-email/components";

export interface VerifyEmailProps {
  name?: string;
  /** Full verification URL — typically `${appUrl}/api/auth/verify?token=${token}`. */
  verificationUrl: string;
}

export function VerifyEmail({ name, verificationUrl }: VerifyEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Verify your email address to activate your Quaesitor account.</Preview>
      <Body style={body}>
        <Container style={container}>
          <Heading style={h1}>Verify your email</Heading>
          <Text style={text}>Hi {name || "there"},</Text>
          <Text style={text}>
            Confirm your email address to activate your Quaesitor account. This
            link expires in 24 hours.
          </Text>
          <Button style={button} href={verificationUrl}>
            Verify email
          </Button>
          <Text style={muted}>
            Or paste this link into your browser:
            <br />
            <Link style={link} href={verificationUrl}>
              {verificationUrl}
            </Link>
          </Text>
          <Hr style={hr} />
          <Text style={footer}>
            If you didn’t create an account, you can safely ignore this email.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

VerifyEmail.subject = (_props: VerifyEmailProps) => "Verify your email";

const body = {
  backgroundColor: "#f4f5f7",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  margin: 0,
  padding: "24px 0",
};

const container = {
  backgroundColor: "#ffffff",
  borderRadius: "8px",
  maxWidth: "560px",
  margin: "0 auto",
  padding: "32px 40px",
  border: "1px solid #e5e7eb",
};

const h1 = {
  color: "#4f46e5",
  fontSize: "24px",
  fontWeight: 700,
  margin: "0 0 16px",
};

const text = {
  color: "#1f2937",
  fontSize: "15px",
  lineHeight: "24px",
  margin: "0 0 12px",
};

const muted = {
  color: "#6b7280",
  fontSize: "13px",
  lineHeight: "20px",
  margin: "16px 0 0",
};

const link = {
  color: "#4f46e5",
  textDecoration: "underline",
  wordBreak: "break-all" as const,
};

const button = {
  backgroundColor: "#4f46e5",
  borderRadius: "6px",
  color: "#ffffff",
  display: "inline-block",
  fontSize: "15px",
  fontWeight: 600,
  padding: "12px 24px",
  textDecoration: "none",
};

const hr = {
  borderColor: "#e5e7eb",
  margin: "24px 0",
};

const footer = {
  color: "#6b7280",
  fontSize: "12px",
  lineHeight: "18px",
  margin: "0",
};

export default VerifyEmail;
